package com.tuxdave.GUI;

import JComponents.JPlaceHolderTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class Gui extends JFrame {
    private JPanel panel1;
    private JComboBox sessoBox;
    private JComboBox cittaBox;
    private JButton calcolaButton;
    private JTextField codiceFiscaleTextField;
    private JPlaceHolderTextField cognomeEdit;
    private JPlaceHolderTextField nomeEdit;
    private JDatePicker datePicker;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
        cognomeEdit = new JPlaceHolderTextField();
        Font cognomeEditFont = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, cognomeEdit.getFont());
        if (cognomeEditFont != null) cognomeEdit.setFont(cognomeEditFont);
        cognomeEdit.setPlaceHolder("Cognome...");
        cognomeEdit.setToolTipText("Cognome...");
        panel1.add(cognomeEdit, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        nomeEdit = new JPlaceHolderTextField();
        Font nomeEditFont = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, nomeEdit.getFont());
        if (nomeEditFont != null) nomeEdit.setFont(nomeEditFont);
        nomeEdit.setPlaceHolder("Cognome...");
        nomeEdit.setText("ciao...");
        nomeEdit.setToolTipText("Cognome...");
        panel1.add(nomeEdit, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JDatePicker nestedForm1 = new JDatePicker();
        panel1.add(nestedForm1.$$$getRootComponent$$$(), new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        sessoBox = new JComboBox();
        Font comboBox1Font = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, sessoBox.getFont());
        if (comboBox1Font != null) sessoBox.setFont(comboBox1Font);
        panel1.add(sessoBox, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cittaBox = new JComboBox();
        Font comboBox2Font = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, cittaBox.getFont());
        if (comboBox2Font != null) cittaBox.setFont(comboBox2Font);
        panel1.add(cittaBox, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        calcolaButton = new JButton();
        Font button1Font = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, calcolaButton.getFont());
        if (button1Font != null) calcolaButton.setFont(button1Font);
        calcolaButton.setText("Button");
        panel1.add(calcolaButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        codiceFiscaleTextField = new JTextField();
        Font textField1Font = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, codiceFiscaleTextField.getFont());
        if (textField1Font != null) codiceFiscaleTextField.setFont(textField1Font);
        panel1.add(codiceFiscaleTextField, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    {
        add(panel1);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setResizable(false);
    }
}
